version: '3.7'
services:

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: patrick
      MYSQL_PASSWORD: password
    volumes:
      - db-local:/var/lib/mysql
    ports:
      - 3306:3306

  # mailcatcher:
  #   image: schickling/mailcatcher
  #   container_name: smtp
  #   ports:
  #     - 1080:1080
  #     - 1025:1025

volumes:
  db-local:
    external: true